null check for:
java.lang.NullPointerException: Cannot invoke
"com.servoy.j2db.persistence.Form.getFlattenedObjects(java.util.Comparator)"
because the return value of
"com.servoy.j2db.FlattenedSolution.getFlattenedForm(com.servoy.j2db.persistence.IPersist)"
is null
        at com.servoy.j2db.server.ngclient.FormElementHelper.generateFormComponentPersists(FormElementHelper.java:217)
        at com.servoy.j2db.server.ngclient.FormElementHelper.generateFormComponentElements(FormElementHelper.java:205)
        at com.servoy.j2db.server.ngclient.FormElementHelper.getFormComponentFromCache(FormElementHelper.java:172)
        at com.servoy.j2db.server.ngclient.FormElementHelper.getFormComponentCache(FormElementHelper.java:156)
        at com.servoy.j2db.server.ngclient.property.types.FormComponentPropertyType.toRhinoValue(FormComponentPropertyType.java:155)
        at com.servoy.j2db.server.ngclient.property.types.NGConversions.convertSabloComponentToRhinoValue(NGConversions.java:435)
        at com.servoy.j2db.server.ngclient.component.RuntimeWebComponent.get(RuntimeWebComponent.java:315)
        at com.servoy.j2db.util.Utils.getScriptableString(Utils.java:3279)