SVY-18754 Fix the Cross Site Script stuff that Snyk.io reports
fixed another null pointer:

java.lang.NullPointerException: Cannot invoke
"javax.servlet.http.HttpServletResponse.setStatus(int)" because
"response" is null
	at com.servoy.j2db.server.ngclient.AngularIndexPageWriter.solutionMissing(AngularIndexPageWriter.java:304)
~[?:?]
	at com.servoy.j2db.server.ngclient.AngularIndexPageWriter.getFlattenedSolution(AngularIndexPageWriter.java:271)
~[?:?]
	at com.servoy.j2db.server.ngclient.StatelessLoginHandler.mustAuthenticate(StatelessLoginHandler.java:99)
~[?:?]