Exception in thread "AWT-EventQueue-2" java.lang.NoClassDefFoundError: org/apache/commons/fileupload/FileItem
must inline stuff for SmartClient because JSUpload is a return type of
JSApplication