fix for recreateForms and reloadSolution because of modules changes (that triggers also package changes)
java.lang.NullPointerException: Cannot invoke
"com.servoy.j2db.scripting.IExecutingEnviroment.getSolutionScope()"
because the return value of
"com.servoy.j2db.server.ngclient.INGApplication.getScriptEngine()" is
null
	at com.servoy.j2db.server.ngclient.component.RuntimeLegacyComponent.<init>(RuntimeLegacyComponent.java:119)
	at com.servoy.j2db.server.ngclient.WebFormUI.contributeComponentToElementsScope(WebFormUI.java:270)
	at com.servoy.j2db.server.ngclient.WebFormUI.init(WebFormUI.java:174)
	at com.servoy.j2db.server.ngclient.WebFormUI.<init>(WebFormUI.java:131)
	at com.servoy.j2db.server.ngclient.component.WebFormController.initFormUI(WebFormController.java:104)
	at com.servoy.j2db.debug.DebugNGClient.refreshForms(DebugNGClient.java:359)
	at com.servoy.j2db.debug.DebugNGClient.recreateForms(DebugNGClient.java:315)
	at com.servoy.eclipse.core.Activator$6$5.ngPackagesChanged(Activator.java:946)



	reloadDebugSolution(Solution) : void -
com.servoy.j2db.debug.DebugClientHandler
	run() : void - com.servoy.eclipse.core.Activator.initialize().new Job()
{...}.run(...).new IActiveProjectListener()
{...}.activeProjectUpdated(...).new Runnable() {...}
		[constructor] new Runnable() {...} -
com.servoy.eclipse.core.Activator.initialize().new Job()
{...}.run(...).new IActiveProjectListener()
{...}.activeProjectUpdated(...)
			activeProjectUpdated(ServoyProject, int) : void -
com.servoy.eclipse.core.Activator.initialize().new Job()
{...}.run(...).new IActiveProjectListener() {...}
		[callers]