Related to SVY-19890
Fixed an exception noticed while working with Diana on that case:

2025-06-17 09:27:19,227 ERROR [AWT-EventQueue-0]
com.servoy.j2db.util.Debug - Something goes wrong with setting the recod
on the form: show [7785CDED-97E4-4263-9915-F0C0F6066570 tagsInDialogs]
java.lang.RuntimeException: Something goes wrong with setting the recod
on the form: show
	at com.servoy.j2db.server.ngclient.component.WebFormController.refreshAllPartRenderers(WebFormController.java:320)
~[?:?]
	at com.servoy.j2db.BasicFormController.valueChanged(BasicFormController.java:593)
~[?:?]
	at com.servoy.j2db.BasicFormController.notifyVisible(BasicFormController.java:384)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController.notifyVisible(WebFormController.java:783)
~[?:?]
	at com.servoy.j2db.debug.DebugNGClient.refreshForms(DebugNGClient.java:328)
~[?:?]
	at com.servoy.j2db.debug.DebugNGClient.refreshPersists(DebugNGClient.java:386)
~[?:?]
	at com.servoy.j2db.debug.DebugClientHandler.refreshDebugClients(DebugClientHandler.java:151)
~[?:?]
	at com.servoy.eclipse.core.Activator$6$2$1.run(Activator.java:893)
~[?:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[?:?]
Caused by: java.lang.RuntimeException: Error setting record Record[...]
	at com.servoy.j2db.server.ngclient.DataAdapterList.setRecord(DataAdapterList.java:751)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController.refreshAllPartRenderers(WebFormController.java:308)
~[?:?]
	... 20 more
Caused by: java.lang.IllegalStateException: no current window set
	at org.sablo.websocket.CurrentWindow.get(CurrentWindow.java:40) ~[?:?]
	at org.sablo.websocket.impl.ClientService.executeAsyncServiceCall(ClientService.java:139)
~[?:?]
	at org.sablo.websocket.impl.ClientService.executeAsyncServiceCall(ClientService.java:133)
~[?:?]
	at com.servoy.j2db.server.ngclient.NGRuntimeWindow.sendTitle(NGRuntimeWindow.java:396)
~[?:?]
	at com.servoy.j2db.server.ngclient.NGRuntimeWindow.setTitle(NGRuntimeWindow.java:296)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController$1.dataProviderOrRecordChanged(WebFormController.java:160)
~[?:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.pushChangedValues(DataAdapterList.java:846)
~[?:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.setRecord(DataAdapterList.java:734)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController.refreshAllPartRenderers(WebFormController.java:308)
~[?:?]
	... 20 more