JavaException: org.apache.wicket.WicketRuntimeException: Cannot modify component hierarchy after render phase has started (page version cant change then anymore)
make sure that the events that are added during a request cycle are really also done in that request.
Case: SVY-3080