null pointer fix for:
java.lang.NullPointerException: Cannot load from int array because
"this.operators" is null
366	at com.servoy.j2db.persistence.Relation.checkKeyTypes(Relation.java:806)
367	at com.servoy.eclipse.model.builder.ServoyRelationBuilder.checkRelation(ServoyRelationBuilder.java:406)
368	at com.servoy.eclipse.model.builder.ServoyBuilder$4.visit(ServoyBuilder.java:1943)
369	at com.servoy.j2db.persistence.AbstractBase.acceptVisitor(AbstractBase.java:543)
370	at com.servoy.j2db.persistence.AbstractBase.acceptVisitor(AbstractBase.java:549)
371	at com.servoy.eclipse.model.builder.ServoyBuilder.checkServoyProject(ServoyBuilder.java:1843)