fix for if lastLogin was not in the token
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String,
String)" because "headerValue" is null
  com.servoy.j2db.server.ngclient.auth.CloudStatelessAccessManager.sanitizeHeader(CloudStatelessAccessManager.java:657)
  com.servoy.j2db.server.ngclient.auth.CloudStatelessAccessManager.checkCloudPermissions(CloudStatelessAccessManager.java:175)
  com.servoy.j2db.server.ngclient.StatelessLoginHandler.checkUser(StatelessLoginHandler.java:173)
  com.servoy.j2db.server.ngclient.StatelessLoginHandler.mustAuthenticate(StatelessLoginHandler.java:140)
  com.servoy.eclipse.ngclient.ui.IndexPageFilter.doFilter(IndexPageFilter.java:108)
  org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)