Exception in thread "AWT-EventQueue-2" java.lang.NoClassDefFoundError: org/apache/commons/fileupload/FileItem
also just catch throwable so that for example smartclient will start
through