SVY-15896 Improve performance of saving (related) records.
fix for:
java.lang.NullPointerException: Cannot read the array length because
"this.operators" is null
	at com.servoy.j2db.persistence.Relation.getForeignColumnsForEqualConditions(Relation.java:833)
~[servoy_shared_2021.3.0.3642.jar:?]
	at com.servoy.j2db.dataprocessing.RowManager.lambda$3(RowManager.java:698)
~[servoy_shared_2021.3.0.3642.jar:?]
	at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3652)
~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
~[?:?]
	at com.servoy.j2db.dataprocessing.RowManager.fireNotifyChange(RowManager.java:695)
~[servoy_shared_2021.3.0.3642.jar:?]

	because it could be that the operators or the foreign dataproviders are
not fully loaded yet. They are not asked for once.