null check for:
java.lang.NullPointerException: Cannot invoke "java.util.List.size()"
because "columns" is null
 at com.servoy.j2db.dataprocessing.SQLGenerator.getEmptyDataSetForDummyQuery(SQLGenerator.java:1103)
 at com.servoy.j2db.dataprocessing.FoundSet.performQuery(FoundSet.java:7782)
 at com.servoy.j2db.dataprocessing.FoundSet.refreshFromDBInternal(FoundSet.java:495)
 at com.servoy.j2db.dataprocessing.FoundSet.refreshFromDB(FoundSet.java:424)