fix for:
org.json.JSONException: JSONObject["parentForm"] not found.
 at org.json.JSONObject.get(JSONObject.java:423)
 at org.json.JSONObject.getString(JSONObject.java:594)
 at com.servoy.j2db.server.ngclient.NGClientWebsocketSession$3.run(NGClientWebsocketSession.java:303)
 at com.servoy.j2db.server.headlessclient.eventthread.Event.execute(Event.java:55)
 at com.servoy.j2db.server.ngclient.eventthread.NGEvent.execute(NGEvent.java:62)
 
 parent form doesn't have to be set (for a dialog)