SVY-19841: When multiply tabpanels are places then with having 2 tabs in different tabpanels can hide the other because of nested relations
fix for that Set.of() doesn't allow duplicate values:

java.lang.IllegalArgumentException: duplicate element:
build_error_dashboard_class
	at java.base/java.util.ImmutableCollections$SetN.<init>(Unknown Source)
~[?:?]
	at java.base/java.util.Set.of(Unknown Source) ~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSet.notifyChange(FoundSet.java:6340)
~[?:?]
	at com.servoy.j2db.dataprocessing.RowManager.lambda$10(RowManager.java:760)
~[?:?]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at com.servoy.j2db.dataprocessing.RowManager.fireNotifyChange(RowManager.java:760)
~[?:?]
	at com.servoy.j2db.dataprocessing.RowManager.fireNotifyChange(RowManager.java:728)
~[?:?]
	at com.servoy.j2db.dataprocessing.RowManager.foundSetChanged(RowManager.java:1597)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager$GlobalFoundSetEventListener.foundSetChanged(FoundSetManager.java:2852)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSet$2.run(FoundSet.java:6125)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSet.fireFoundSetEvent(FoundSet.java:6137)
~[?:?]
	at com.servoy.j2db.dataprocessing.SwingRelatedFoundSet.fireFoundSetEvent(SwingRelatedFoundSet.java:146)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSet.fireFoundSetEvent(FoundSet.java:6090)
~[?:?]
	at com.servoy.j2db.dataprocessing.EditRecordList.fireEvents(EditRecordList.java:2067)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.refreshFoundSetsFromDB(FoundSetManager.java:424)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.refreshFoundSetsFromDBforFilterAndGetAffectedTables(FoundSetManager.java:459)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.lambda$19(FoundSetManager.java:1408)
~[?:?]
	at java.base/java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.setTableFilters(FoundSetManager.java:1407)
~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.setTenantValue(FoundSetManager.java:4074)
~[?:?]
	at com.servoy.j2db.scripting.JSSecurity.setTenantValue(JSSecurity.java:195)
~[?:?]