java.lang.NullPointerException: Cannot invoke "org.sablo.IWebObjectContext.getProperties(org.sablo.specification.property.IPropertyType)" because "this.webObjectContext" is null at com.servoy.j2db.server.ngclient.property.types.DataproviderTypeSabloValue.dataProviderOrRecordChanged(DataproviderTypeSabloValue.java:288) ~[servoy_ngclient_2020.12.0.3622.jar:?] at com.servoy.j2db.server.ngclient.property.types.DataproviderTypeSabloValue$2.valueChanged(DataproviderTypeSabloValue.java:174) ~[servoy_ngclient_2020.12.0.3622.jar:?] at com.servoy.j2db.dataprocessing.FoundSet.fireAggregateModificationEvent(FoundSet.java:5915) ~[j2db.jar:2020.12.0.3622]