Fix for NPE
java.lang.NullPointerException: Cannot invoke
"com.servoy.j2db.persistence.IDataProvider.getDataProviderID()" because
"dependedDataProviders[i]" is null
        at com.servoy.j2db.server.ngclient.property.types.ValueListTypeSabloValue.getDataLinks(ValueListTypeSabloValue.java:352)
~[?:?]
        at com.servoy.j2db.server.ngclient.property.types.ValueListTypeSabloValue.initializeIfPossibleAndNeeded(ValueListTypeSabloValue.java:305)
~[?:?]
        at com.servoy.j2db.server.ngclient.property.types.ValueListTypeSabloValue.attachToBaseObject(ValueListTypeSabloValue.java:200)
~[?:?]