fixing if a new java version is used to compile that can result in a different serialVersionUID
com.servoy.j2db.util.SafeArrayList; local class incompatible: stream
classdesc serialVersionUID = -47920
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
[{'clientId': '', 'solutionName': ''}]
java.io.InvalidClassException: com.servoy.j2db.util.SafeArrayList; local
class incompatible: stream classdesc serialVersionUID =
-4792011112490329702, local class serialVersionU
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
~[?:?]