fix for exception below
 also do catch the exception in the WebController when pusing the record
to the ui. so that we can report which form it is that has these
problems.

 But if the foundset property type gets a foundset where the datasource
is null (prototype records with a NoTableFoundset) then just assume it
is still null.

ERROR com.servoy.j2db.util.Debug - Error setting record PrototypeState[]
COLUMS: getChangedData,getDataSource,getException,revertChanges,isEditing,save,getPKs,isNew,hasChangedData,rollbackChanges,createMarkers,isRelatedFoundSetLoaded,getFoundset,deleteRecord,
on form FormController[form: BreadCrumbShortList, fs size:0,visible:
true, selected record: null,destroyed:false] on DAL
DAL[form:FormController[form: BreadCrumbShortList, fs size:0,visible:
true, selected record: null,destroyed:false], record:PrototypeState[]
COLUMS: getChangedData,getDataSource,getException,revertChanges,isEditing,save,getPKs,isNew,hasChangedData,rollbackChanges,createMarkers,isRelatedFoundSetLoaded,getFoundset,deleteRecord,]
	at /Users/wouterboers/Servoy
workspaces/Servoy_2021.x/nb_navigation/nb_navigation.js:1452
	at /Users/wouterboers/Servoy
workspaces/Servoy_2021.x/nb_navigation/nb_navigation.js:1314
	at /Users/wouterboers/Servoy
workspaces/Servoy_2021.x/nb_navigation/nb_navigation.js:1170
(nav_showHome)
	at /Users/wouterboers/Servoy
workspaces/Servoy_2021.x/nb_forms/forms/MainBody.js:19 (onShow)
java.lang.RuntimeException: Error setting record PrototypeState[]
COLUMS: getChangedData,getDataSource,getException,revertChanges,isEditing,save,getPKs,isNew,hasChangedData,rollbackChanges,createMarkers,isRelatedFoundSetLoaded,getFoundset,deleteRecord,
on form FormController[form: BreadCrumbShortList, fs size:0,visible:
true, selected record: null,destroyed:false] on DAL
DAL[form:FormController[form: BreadCrumbShortList, fs size:0,visible:
true, selected record: null,destroyed:false], record:PrototypeState[]
COLUMS: getChangedData,getDataSource,getException,revertChanges,isEditing,save,getPKs,isNew,hasChangedData,rollbackChanges,createMarkers,isRelatedFoundSetLoaded,getFoundset,deleteRecord,]
	at com.servoy.j2db.server.ngclient.DataAdapterList.setRecord(DataAdapterList.java:681)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController.refreshAllPartRenderers(WebFormController.java:264)
~[?:?]
	at com.servoy.j2db.BasicFormController.valueChanged(BasicFormController.java:516)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.BasicFormController.notifyVisible(BasicFormController.java:364)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.server.ngclient.component.WebFormController.notifyVisible(WebFormController.java:732)
~[?:?]
	at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:247)
~[?:?]
	at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:414)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:97)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:87)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:130)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.EventDispatcher.suspend(EventDispatcher.java:246)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.websocket.WebsocketEndpoint.waitResponse(WebsocketEndpoint.java:572)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.websocket.BaseWindow.sendSyncMessage(BaseWindow.java:492)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.websocket.BaseWindow.invokeApi(BaseWindow.java:1060)
~[sablo_2022.6.0.3782.jar:?]
	at com.servoy.j2db.server.ngclient.NGClientWindow.invokeApi(NGClientWindow.java:175)
~[?:?]
	at org.sablo.websocket.BaseWindow.invokeApi(BaseWindow.java:1009)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.WebComponent.invokeApi(WebComponent.java:168)
~[sablo_2022.6.0.3782.jar:?]
	at com.servoy.j2db.server.ngclient.scripting.WebComponentFunction.call(WebComponentFunction.java:58)
~[?:?]
	at com.servoy.j2db.server.ngclient.component.RuntimeWebComponent$5.call(RuntimeWebComponent.java:376)
~[?:?]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1487)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3534)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
~[org.eclipse.dltk.javascript.rhino_2022.6.0.3782.jar:?]
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:727)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393)
~[?:?]
	at com.servoy.j2db.BasicFormController.executeFunction(BasicFormController.java:1082)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.BasicFormController.executeFormMethod(BasicFormController.java:798)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.BasicFormController.executeOnShowMethod(BasicFormController.java:666)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.BasicFormController.access$2(BasicFormController.java:659)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.BasicFormController$1.run(BasicFormController.java:390)
~[servoy_shared_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.Event$1.run(Event.java:97)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.Event.execute(Event.java:87)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:130)
~[sablo_2022.6.0.3782.jar:?]
	at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89)
~[sablo_2022.6.0.3782.jar:?]
	at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:57)
~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke
"Object.hashCode()" because "<parameter1>" is null
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:?]
	at com.servoy.j2db.dataprocessing.FoundSetManager.getTableFilterParams(FoundSetManager.java:1435)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.dataprocessing.FoundSet.getSerializedQuery(FoundSet.java:5530)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.dataprocessing.FoundSet.addFoundSetEventListener(FoundSet.java:7304)
~[servoy_shared_2022.6.0.3782.jar:?]
	at com.servoy.j2db.server.ngclient.property.FoundsetTypeViewport.setFoundset(FoundsetTypeViewport.java:64)
~[?:?]
	at com.servoy.j2db.server.ngclient.property.FoundsetTypeSabloValue.updateFoundset(FoundsetTypeSabloValue.java:462)
~[?:?]
	at com.servoy.j2db.server.ngclient.property.FoundsetTypeSabloValue.updateFoundset(FoundsetTypeSabloValue.java:384)
~[?:?]
	at com.servoy.j2db.server.ngclient.property.FoundsetTypeSabloValue.dataProviderOrRecordChanged(FoundsetTypeSabloValue.java:538)
~[?:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.pushChangedValues(DataAdapterList.java:765)
~[?:?]
	at com.servoy.j2db.server.ngclient.DataAdapterList.setRecord(DataAdapterList.java:652)
~[?:?]
	... 39 more