SVY-11070 loginForm and forms from login solutions don't get notifyVisible(false)
try not to hide it right way, the login form is still visible in the
browser, and the hide/destroy will remove everything but if between the
show of the main a call to the client is done then the form will be
touched again:

2017-06-29 09:28:23,527 ERROR
[Executor,uuid:ed149a23-1ef4-442d-b9da-2c3cc4037926]
org.sablo.websocket.WebsocketEndpoint - Error: Can't show form: login
because it is not allowed in the client [ ]
java.lang.IllegalStateException: Can't show form: login because it is
not allowed in the client
    at
com.servoy.j2db.server.ngclient.NGClientWindow.touchForm(NGClientWindow.java:227)
    at
com.servoy.j2db.server.ngclient.NGRuntimeWindowManager.executeMethod(NGRuntimeWindowManager.java:90)
    at
org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:333)